Feature/database opzet + .gitignore
ProjectMaasgroep18/ms18-applicatie pull request #4
Opened 2023-09-25 06:43 UTC by Kevin4032

Met deze eerste database opzet ben ik zeer content.
We maken gebruik van default constraint voor datetime op insert.
We maken gebruik van sequences ipv identityproperty zodat wij in controle zijn over de nummers, of kunnen zijn.
We zetten een no action op delete en update, zodat wij in controle zijn van onze data.

Plus een gitignore.

Kanttekening;
- Nullability van properties; nog even kijken is hoe onze objecten goed in elkaar passen voor wat betreft nullability van de data, ik denk dat we goed zitten.
- Deze commits bevatten bewust geen migrations, die heb ik lokaal wel getest. Als er duidelijkheid is over de nullability en ik wat testdata gemaakt heb dan gooi ik er een eerste migration in. 

Persoonlijk ben ik voorstander geen migrations erin te zetten tot we als geheel project alles succesvol kunnen bouwen en onze data en datastructuur klopt. Anders blijf je hannesen met 'alter tables' en shit.

2023-09-25 08:40 UTC, Joossensei commented
Hoi @Kevin4032, is het misschien een idee (ik heb dit namelijk ook in mijn werk situatie) om de createdatetime, updatedatetime, createuser en updateuser mee te nemen? 
Ik doe in mijn werk veel met databases en wij hebben een standaard structuur van id, createdatetime, updatedatetime, createuser en updateuser. Deze vind ik zelf bij het bijvoorbeeld debuggen van je databaseverkeer best handig (en je hebt natuurlijk vastgelegd wie wat en wanneer doet). Ik hoor graag jouw take hierop 😄

2023-09-25 09:25 UTC, TomBaakHR requested changes
@Kevin4032 zou jij alle database bestanden die relevant zijn voor ons team in een `/ms18-applicatie/ms18-database/team-c` mapje willen zetten? Dan loopt alles goed met het codeowner verhaal.

2023-09-30 10:20 UTC, Kevin4032 commented
> Hoi @Kevin4032, is het misschien een idee (ik heb dit namelijk ook in mijn werk situatie) om de createdatetime, updatedatetime, createuser en updateuser mee te nemen? Ik doe in mijn werk veel met databases en wij hebben een standaard structuur van id, createdatetime, updatedatetime, createuser en updateuser. Deze vind ik zelf bij het bijvoorbeeld debuggen van je databaseverkeer best handig (en je hebt natuurlijk vastgelegd wie wat en wanneer doet). Ik hoor graag jouw take hierop 😄

Is gefixt met de laatste update.

2023-09-30 10:20 UTC, Kevin4032 commented
> @Kevin4032 zou jij alle database bestanden die relevant zijn voor ons team in een `/ms18-applicatie/ms18-database/team-c` mapje willen zetten? Dan loopt alles goed met het codeowner verhaal.

De context heb ik er buiten laten staan, 'onze' spullen erin, maar ook stukje 'photos'. De photos heb ik niks meer aan gedaan, dat ligt eigenlijk bij ander groepje.

2023-09-30 10:22 UTC, Kevin4032 commented
Voor de goede orde, ik heb ook testdata toegevoegd, eerste opzetje, dat alle objecten, nullability etc te zien zijn.

2023-09-30 13:04 UTC, Kevin4032 commented
Heb ook 'admin' een stukje uitgebreid met een many-to-many van 'members' en 'permissions' voor het 'receipt' stuk.

2023-10-09 17:48 UTC, Kevin4032 commented
Nu met checkconstraint!

2023-10-21 09:28 UTC, TomBaakHR approved these changes
Ziet er goed uit. Codeowners klopt nu ook

2023-11-13 18:58 UTC, merged