Feature/add get google calendar
ProjectMaasgroep18/ms18-applicatie pull request #8
Opened 2023-10-23 14:21 UTC by TimGrootscholten

2023-10-23 14:27 UTC, jimtronchet requested changes

2023-10-23 14:27 UTC, jimtronchet commented on ms18-applicatie/Controllers/CalendarController/CalendarController.cs
> +
whiteline :(

2023-10-23 14:27 UTC, jimtronchet commented on ms18-applicatie/ms18-applicatie.csproj
> +        <UserSecretsId>9c7c241f-7783-4d86-b780-c0b6052fafcf</UserSecretsId>
smart

2023-10-23 14:27 UTC, TimGrootscholten commented on ms18-applicatie/Controllers/CalendarController/CalendarController.cs
> +
fixed

2023-10-23 14:27 UTC, TimGrootscholten commented on ms18-applicatie/ms18-applicatie.csproj
> +        <UserSecretsId>9c7c241f-7783-4d86-b780-c0b6052fafcf</UserSecretsId>
goed he XD

2023-10-23 14:27 UTC, jimtronchet approved these changes

2023-10-23 16:39 UTC, TomBaakHR requested changes
@TimGrootscholten zou je de models willen verplaatsen naar `Models/team-a/` en de Controllers naar `Controllers/team-c/`? Hiermee wordt het github codeowner deel goed afgehandeld.

2023-10-23 18:19 UTC, Vinciepincie approved these changes

2023-11-13 18:59 UTC, TomBaakHR approved these changes

2023-11-13 19:13 UTC, merged